version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: bash -c "while true; do echo hello; sleep 2; done"
    volumes:
      - .:/var/www
    ports:
      - "8000:8005"
    networks:
        - flask_api_demo
volumes:
  postgres-data:
    driver: local
networks:
  flask_api_demo: