version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: ["python3", "-u", "./app.py"]
    volumes:
      - .:/var/www
    ports:
      - "8000:8005"
    networks:
        - flask_api_demo
volumes:
  postgres-data:
    driver: local
networks:
  flask_api_demo: